Added basic direct request smoke test
smartcontractkit/integrations-framework pull request #30
Opened 2021-07-21 12:28 UTC by skudasov

2021-07-21 15:25 UTC, jleeh requested changes

2021-07-21 15:25 UTC, jleeh commented on client/chainlink_models.go
> +func ObservationSourceConsumerTxEncode(url string) string {
From looking at this, looks like it should be its own gotemplate object like the others.

2021-07-23 08:53 UTC, skudasov commented on config/config.yml
> +        chain_id: 1337
Compatibility with geth/hh compose changes.

2021-07-26 12:08 UTC, jleeh approved these changes

2021-07-28 13:45 UTC, merged