VRF test
smartcontractkit/integrations-framework pull request #34
Opened 2021-07-26 13:52 UTC by skudasov

2021-07-26 14:44 UTC, skudasov commented on client/chainlink.go
> +func (c *chainlink) ReadVRFKeys() (*VRFKeys, error) {
Need to merge VRF key generation in compose first https://github.com/smartcontractkit/chainlink-node-compose/pull/10

2021-08-04 11:12 UTC, jleeh requested changes
One tiny comment, but nice work.

2021-08-04 11:12 UTC, jleeh commented on suite/contracts/contracts_vrf_test.go
> +				err = coordinator.RegisterProvingKey(s.Wallets.Default(), big.NewInt(1), oracleAddr, provingKey, actions.EncodeOnChainExternalJobID(jobUUID))
Just be aware of line size here, put the function params onto new lines.

2021-08-04 19:59 UTC, jleeh approved these changes

2021-08-05 09:13 UTC, merged