Expand OCR test time
smartcontractkit/integrations-framework pull request #58
Opened 2021-08-09 20:29 UTC by kalverra

Quick fix for consistency issues. Talking to @jleeh about getting a blockchain method to subscribe to new blocks, to make this cleaner and more consistent than the basic check-sleep loop.

2021-08-09 20:59 UTC, tateexon approved these changes
Looks good to me

2021-08-09 21:57 UTC, jleeh requested changes

2021-08-09 21:57 UTC, jleeh commented on suite/contracts/contracts_ocr_test.go
> +			for i := 0; i < 60; i++ {
Use the retry lib that Sergey brought in, like here:
https://github.com/smartcontractkit/integrations-framework/blob/main/suite/contracts/contracts_runlog_test.go#L101

2021-08-10 14:40 UTC, kalverra commented
# Improved OCR Test
Improved this to utilize the new block header subscription to poll only for new rounds, and included a value change check. The previous test time was ~60-70 seconds, this one includes another check, and consistently runs in ~70-75 seconds

2021-08-10 14:51 UTC, jleeh requested changes

2021-08-10 14:51 UTC, jleeh commented on suite/contracts/contracts_ocr_test.go
> +					ObservationSource:  client.ObservationSourceSpec(fmt.Sprintf("%s/variable", adapter.ClusterURL())),
I'd add this endpoint within the adapter interface so we don't need to do this string formatting each time.

2021-08-10 16:28 UTC, jleeh approved these changes

2021-08-10 16:28 UTC, merged