Gas estimation for FM
smartcontractkit/integrations-framework pull request #66
Opened 2021-08-13 11:13 UTC by skudasov

Gas estimation for FM to fund it for one tx.

2021-08-16 19:39 UTC, kalverra requested changes

2021-08-16 19:39 UTC, kalverra commented on client/blockchain.go
> +	CalculateTxGasCostWithBuffer(maxGasUsedValue *big.Int) (*big.Float, error)
`CalculateTxGasCostWithBuffer` seems needlessly wordy, and implies that there is a method `CalculateTxGasCost**Without**Buffer`.

A better name I think is `CalculateTxGas`

2021-08-17 08:18 UTC, skudasov commented on suite/refill/eth_refill_test.go
> +			Expect(err).Should(HaveOccurred())
We tried to check if a node has some errors when there is not enough ETH to perform submission, but there is no run created and no errors, so we need to wait for round timeout.

2021-08-17 13:16 UTC, kalverra requested changes

2021-08-17 13:16 UTC, kalverra commented on suite/refill/eth_refill_test.go
> +			Expect(err).Should(HaveOccurred())
Can we get another check to make sure that the error is a _round timeout_? I see the potential for other errors sneaking through here.

2021-08-17 14:04 UTC, kalverra approved these changes

2021-08-17 14:34 UTC, merged