Add re-org env for Ethereum
smartcontractkit/integrations-framework pull request #87
Opened 2021-09-01 12:45 UTC by skudasov

Helm resource for Geth re-org network

2021-09-01 15:11 UTC, tateexon commented on environment/k8s_environment_helm_test.go
> +var _ = XDescribe("Environment with geth re-org functionality @helm", func() {
Did you want this to still be a pending test?

2021-09-02 09:22 UTC, skudasov commented on contracts/ethereum_reorg_util.go
> +	DAGAwaitTimeout = 120 * time.Second
Around 30s, depends on K8s resources.

2021-09-02 11:07 UTC, jleeh requested changes
Overall, nice clean implementation of Helm.

2021-09-02 11:07 UTC, jleeh commented on environment/k8s_helm_resource.go
> +	sd := make([]*ServiceDetails, 0)
This function can just be the same as the original manfiest deployer? All it's doing is looping over the ports forwarded.

2021-09-02 11:07 UTC, jleeh commented on environment/k8s_helm_resource.go
> +type K8sHelmManifest struct {
Rename this to `HelmChart`

2021-09-02 11:07 UTC, jleeh commented on environment/k8s_helm_resource.go
> +func (k *K8sHelmManifest) Teardown() error {
This should close opened ports like the original deployer does.

2021-09-02 11:07 UTC, jleeh commented on environment/k8s_helm_resource.go
> +		values:      make(map[string]interface{}),
I don't see this being used?

2021-09-02 11:07 UTC, jleeh commented on environment/k8s_helm_resource.go
> +func NewReorgGethHelmResource() *K8sHelmManifest {
Rename to `NewGethReorgHelmChart`.

2021-09-02 13:42 UTC, jleeh approved these changes

2021-09-02 14:07 UTC, merged